---
AWSTemplateFormatVersion: 2010-09-09

Description: Master IAM Configuration

Resources:
    PlaygroundGroup:
        Type: "AWS::IAM::Group"
        Properties:
            GroupName: Playground
            Path: /

    PlaygroundRole: 
        Type: "AWS::IAM::Role"
        Properties: 
            AssumeRolePolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                - 
                    Effect: "Allow"
                    Principal: 
                        AWS:  !Ref AWS::AccountId
                    Action: "sts:AssumeRole"
                    Condition:
                        Bool:
                            aws:MultiFactorAuthPresent: false
            Path: "/"
            RoleName: sgpg01meetuprole
            ManagedPolicyArns:
            - arn:aws:iam::aws:policy/ReadOnlyAccess
            - arn:aws:iam::aws:policy/AmazonS3FullAccess
            - arn:aws:iam::aws:policy/AmazonLexFullAccess
            Policies:
                - PolicyName: "LambdaRegionLockDown"
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    -
                        Effect: Allow
                        Action:
                            - lambda:*
                            - events:*
                            - iam:ListAttachedRolePolicies
                            - iam:ListRolePolicies
                            - iam:ListRoles
                            - iam:PassRole
                            - kms:ListAliases
                        Resource: "*"
                    - 
                        Effect: Deny
                        Action: lambda:*
                        Resource:
                            - !Sub arn:aws:lambda:us-east-2:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:us-west-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:us-west-2:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:ap-northeast-2:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:ap-south-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:ap-southeast-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:ap-southeast-2:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:ca-central-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:eu-central-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:eu-west-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:eu-west-2:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:eu-west-3:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:sa-east-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:cn-north-1:${AWS::AccountId}:function:*
                            - !Sub arn:aws:lambda:cn-northwest-1:${AWS::AccountId}:function:*

                - PolicyName: "SNSRegionLockDown"
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        -
                            Effect: Allow
                            Action:
                                - SNS:*
                            Resource:
                                - !Sub arn:aws:sns:us-east-1:${AWS::AccountId}:*
                
                - PolicyName: "CloudformationRegionLockDown"
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        -
                            Effect: Allow
                            Action:
                                - cloudformation:*
                            Resource:
                                - !Sub arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/*
                        -
                            Effect: Allow
                            Action:
                                - cloudformation:CreateUploadBucket
                            Resource:
                                - "*"

                - PolicyName: "ConnectFullAccess"
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        -
                            Effect: Allow
                            Action:
                                - connect:*
                                - iam:CreateRole
                                - iam:CreatePolicy
                                - iam:AttachRolePolicy
                                - iam:CreatePolicyVersion
                                - iam:DeletePolicyVersion
                            Resource: "*"

    AssumePolicy: 
        Type: "AWS::IAM::Policy"
        Properties: 
            Groups:
                - !Ref PlaygroundGroup
            PolicyName: "AssumePlaygroundRole"
            PolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                - 
                  Sid: AllowUsersToAssumePlaygroundRole
                  Effect: "Allow"
                  Action: "sts:AssumeRole"
                  Resource: !GetAtt PlaygroundRole.Arn
    
    LambdaExecutionRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                -
                    Effect: "Allow"
                    Principal:
                        Service:
                            - "lambda.amazonaws.com"
                    Action:
                        - "sts:AssumeRole"
            RoleName: LambdaExecutionRole
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
                - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
